# Generated by Django 5.1.1 on 2024-09-04 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Shop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_uz", models.CharField(max_length=50)),
                ("name_ru", models.CharField(max_length=50)),
                ("name_en", models.CharField(max_length=50)),
                ("status", models.SmallIntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_uz", models.CharField(max_length=100)),
                ("name_ru", models.CharField(max_length=100)),
                ("name_en", models.CharField(max_length=100)),
                ("description_uz", models.TextField()),
                ("description_ru", models.TextField()),
                ("description_en", models.TextField()),
                ("status", models.SmallIntegerField(default=0)),
                ("quantity", models.IntegerField(default=0)),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.shop"
                    ),
                ),
            ],
        ),
    ]
