# Generated by Django 5.1.1 on 2024-09-07 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_product_status_alter_shop_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description_en",
            field=models.TextField(
                blank=True, null=True, verbose_name="Mahsulot tavsifi (EN)"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description_ru",
            field=models.TextField(
                blank=True, null=True, verbose_name="Mahsulot tavsifi (RU)"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description_uz",
            field=models.TextField(
                blank=True, null=True, verbose_name="Mahsulot tavsifi (UZ)"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name_en",
            field=models.CharField(max_length=100, verbose_name="Mahsulot nomi (EN)"),
        ),
        migrations.AlterField(
            model_name="product",
            name="name_ru",
            field=models.CharField(max_length=100, verbose_name="Mahsulot nomi (RU)"),
        ),
        migrations.AlterField(
            model_name="product",
            name="name_uz",
            field=models.CharField(max_length=100, verbose_name="Mahsulot nomi (UZ)"),
        ),
        migrations.AlterField(
            model_name="product",
            name="quantity",
            field=models.IntegerField(default=0, verbose_name="Miqdori"),
        ),
        migrations.AlterField(
            model_name="product",
            name="shop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="main.shop",
                verbose_name="Magazin",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="status",
            field=models.SmallIntegerField(
                choices=[(0, "Yangi"), (1, "Tasdiqlanmagan"), (2, "Tasdiqlangan")],
                default=0,
                verbose_name="Holati",
            ),
        ),
        migrations.AlterField(
            model_name="shop",
            name="name_en",
            field=models.CharField(max_length=50, verbose_name="Magazin nomi (EN)"),
        ),
        migrations.AlterField(
            model_name="shop",
            name="name_ru",
            field=models.CharField(max_length=50, verbose_name="Magazin nomi (RU)"),
        ),
        migrations.AlterField(
            model_name="shop",
            name="name_uz",
            field=models.CharField(max_length=50, verbose_name="Magazin nomi (UZ)"),
        ),
        migrations.AlterField(
            model_name="shop",
            name="status",
            field=models.SmallIntegerField(
                choices=[(0, "Yangi"), (1, "Tasdiqlanmagan"), (2, "Tasdiqlangan")],
                default=0,
                verbose_name="Holati",
            ),
        ),
        migrations.AlterField(
            model_name="shop",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shops",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
