# Generated by Django 5.0.3 on 2024-09-17 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_product_description_en_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="shop",
            options={"permissions": [("can_add_shop", "Can add shop")]},
        ),
    ]
