# Generated by Django 5.0.3 on 2024-09-17 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_alter_shop_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="shop",
            options={},
        ),
    ]
