# Generated by Django 5.0.3 on 2024-11-07 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_alter_order_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="card",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="main.card",
            ),
        ),
    ]
