# Generated by Django 5.0.3 on 2024-11-07 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_order_card"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="is_confirmed",
            field=models.BooleanField(default=False),
        ),
    ]
