# Generated by Django 5.0.3 on 2024-11-08 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_product_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="user",
        ),
    ]
